# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
        migrations.AddField(
            model_name='record',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
